FROM jenkins/jenkins:lts-jdk21

USER jenkins

RUN jenkins-plugin-cli --plugins \
    workflow-aggregator \
    git \
    docker-workflow


FROM python:3.11-slim

WORKDIR /app

COPY requirement.txt .
RUN pip install --no-cache-dir -r requirement.txt

COPY app.py .
COPY service.py .

EXPOSE 5000

CMD ["python3", "app.py"]