pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Run tests') {
            agent {
                docker {
                    image 'python:3.11'
                    reuseNode true
                }
            }
            steps {
                sh 'python3 --version'
            }
        }

        stage('Build Water image') {
            steps {
                script {
                    docker.build('water-app:latest', 'cicd')
                }
            }
        }

        stage('Push to local registry') {
            steps {
                script {
                    docker.withRegistry('http://registry:5000') {
                        def img = docker.build('registry:5000/water-app:latest', 'cicd')
                        img.push()
                    }
                }
            }
        }
    }
}