pipeline {
    agent {
        label 'ssh-agent'
    }

    stages {
        stage('Pull image from local registry') {
            steps {
                sh 'docker pull registry:5000/water-app:latest'
            }
        }

        stage('Deploy on host') {
            steps {
                sh 'docker rm -f water-app || true'
                sh 'docker run -d --name water-app -p 5000:5000 registry:5000/water-app:latest'
            }
        }
    }
}